version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shuttlevn-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: ConnectionString
    ports:
      - "8080:8080"