// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShuttleVNBackend.Infrastructure.Persistence;

#nullable disable

namespace ShuttleVNBackend.Infrastructure.Migrations
{
    [DbContext(typeof(ShuttleVnDbContext))]
    [Migration("20260923115223_AllowNullEmployeeAccountAndEmail")]
    partial class AllowNullEmployeeAccountAndEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.Booking.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CourtId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("CourtId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bookings");

                    b.HasAnnotation("CustomExclusion:Constraints", "[{\"parts\":[{\"path\":\"CourtId\",\"op\":\"=\"},{\"path\":\"Date\",\"op\":\"=\"},{\"expr\":\"tsrange(\\u0022Date\\u0022 \\u002B \\u0022StartTime\\u0022, \\u0022Date\\u0022 \\u002B \\u0022EndTime\\u0022)\",\"op\":\"\\u0026\\u0026\"}],\"filter\":\"\\u0022Status\\u0022 \\u003C\\u003E \\u0027Cancelled\\u0027\",\"name\":\"ex_bookings_no_overlap\"}]");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.Booking.BookingStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByEmployee")
                        .HasColumnType("uuid");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldStatus")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ChangedByEmployee");

                    b.ToTable("BookingStatusHistories");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.Booking.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IssuedByEmployee")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Unpaid'");

                    b.HasIndex("InvoiceCode")
                        .IsUnique();

                    b.HasIndex("IssuedByEmployee");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.Court.BadmintonCourt", b =>
                {
                    b.Property<int>("CourtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourtId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CourtId");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.Court.CourtSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduleId"));

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("CourtId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScheduleId");

                    b.HasIndex("CourtId", "DayOfWeek", "OpenTime")
                        .IsUnique();

                    b.ToTable("CourtSchedules");

                    b.HasAnnotation("CustomExclusion:Constraints", "[{\"parts\":[{\"path\":\"CourtId\",\"op\":\"=\"},{\"path\":\"DayOfWeek\",\"op\":\"=\"},{\"expr\":\"tsrange(DATE \\u00272000-01-01\\u0027 \\u002B \\u0022OpenTime\\u0022, DATE \\u00272000-01-01\\u0027 \\u002B \\u0022CloseTime\\u0022)\",\"op\":\"\\u0026\\u0026\"}],\"name\":\"ex_court_schedules_no_overlap\"}]");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.Court.PricingRule", b =>
                {
                    b.Property<int>("PricingRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PricingRuleId"));

                    b.Property<int>("CourtId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PricingRuleId");

                    b.HasIndex("CourtId", "DayOfWeek", "StartTime")
                        .IsUnique();

                    b.ToTable("PricingRules");

                    b.HasAnnotation("CustomExclusion:Constraints", "[{\"parts\":[{\"path\":\"CourtId\",\"op\":\"=\"},{\"path\":\"DayOfWeek\",\"op\":\"=\"},{\"expr\":\"tsrange(DATE \\u00272000-01-01\\u0027 \\u002B \\u0022StartTime\\u0022, DATE \\u00272000-01-01\\u0027 \\u002B \\u0022EndTime\\u0022)\",\"op\":\"\\u0026\\u0026\"}],\"name\":\"ex_pricing_rules_no_overlap\"}]");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.System.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.User.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.User.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EmployeeId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.User.UserAccount", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountId");

                    b.HasIndex("LoginEmail")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.User.VerificationCode", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Email", "Type");

                    b.ToTable("VerificationCodes");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.Booking.Booking", b =>
                {
                    b.HasOne("ShuttleVNBackend.Core.Entities.Court.BadmintonCourt", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShuttleVNBackend.Core.Entities.User.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.Booking.BookingStatusHistory", b =>
                {
                    b.HasOne("ShuttleVNBackend.Core.Entities.Booking.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShuttleVNBackend.Core.Entities.User.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("ChangedByEmployee");

                    b.Navigation("Booking");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.Booking.Invoice", b =>
                {
                    b.HasOne("ShuttleVNBackend.Core.Entities.Booking.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShuttleVNBackend.Core.Entities.User.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("IssuedByEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.Court.CourtSchedule", b =>
                {
                    b.HasOne("ShuttleVNBackend.Core.Entities.Court.BadmintonCourt", null)
                        .WithMany("CourtSchedules")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.Court.PricingRule", b =>
                {
                    b.HasOne("ShuttleVNBackend.Core.Entities.Court.BadmintonCourt", null)
                        .WithMany("PricingRules")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.System.Audit", b =>
                {
                    b.HasOne("ShuttleVNBackend.Core.Entities.User.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.User.Customer", b =>
                {
                    b.HasOne("ShuttleVNBackend.Core.Entities.User.UserAccount", null)
                        .WithOne("Customer")
                        .HasForeignKey("ShuttleVNBackend.Core.Entities.User.Customer", "AccountId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.User.Employee", b =>
                {
                    b.HasOne("ShuttleVNBackend.Core.Entities.User.UserAccount", null)
                        .WithOne("Employee")
                        .HasForeignKey("ShuttleVNBackend.Core.Entities.User.Employee", "AccountId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.Court.BadmintonCourt", b =>
                {
                    b.Navigation("CourtSchedules");

                    b.Navigation("PricingRules");
                });

            modelBuilder.Entity("ShuttleVNBackend.Core.Entities.User.UserAccount", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
